import { hireHref, jobsHref, placementGroups, process, reasons, roles } from '@/lib/roles'
import { RoleAccordion } from '@/components/role-accordion'
import { SiteShell } from '@/components/site-shell'

export function DigitalThingsPage() {
  return <SiteShell><section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Recruitment for digital teams</p><h1 id="hero-title">We find the people who build what&apos;s next.</h1><p className="lede">Digital Things places technical and business talent with ambitious companies.</p><div className="cta-group"><a className="button button-dark" href={hireHref}>Hire talent <span aria-hidden="true">↗</span></a></div></div><div className="role-window" aria-label="Example roles we recruit for"><div className="role-track">{[...roles.map((role) => role.title), 'Platform Engineer', 'Solutions Architect', 'Engineering Manager', ...roles.map((role) => role.title), 'Platform Engineer', 'Solutions Architect', 'Engineering Manager'].map((role, index) => <div className="role-line" key={`${role}-${index}`}>{role}</div>)}</div></div></section>
  <section className="stats" aria-label="Digital Things at a glance"><div><strong>1.5–3 weeks</strong><span>to first shortlist</span></div><div><strong>40+ roles</strong><span>closed this year</span></div><div><strong>5</strong><span>recruiters on the team</span></div></section>
  <section id="roles" className="section roles-section" aria-labelledby="roles-title"><div className="section-intro"><p className="eyebrow">What we do</p><h2 id="roles-title">Roles we place</h2></div><div className="placement-grid">{placementGroups.map((group) => <div className="placement" key={group.title}><h3>{group.title}</h3><RoleAccordion titles={group.roles} /></div>)}</div></section>
  <section id="how-we-work" className="section process-section" aria-labelledby="process-title"><div className="section-intro"><p className="eyebrow">Our approach</p><h2 id="process-title">How we work</h2></div><div className="process-list">{process.map(([title, text], index) => <div className="process-row" key={title}><span className="process-number">0{index + 1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
  <section id="why-us" className="section reasons-section" aria-labelledby="reasons-title"><div className="section-intro"><p className="eyebrow">The difference</p><h2 id="reasons-title">Why teams work with Digital Things</h2></div><div className="reasons-grid">{reasons.map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></section>
  <section className="contact" aria-labelledby="contact-title"><p className="eyebrow">Let&apos;s talk</p><h2 id="contact-title">Tell us who you&apos;re looking for.</h2><p>Give us the shape of the problem. We&apos;ll take it from there.</p><div className="cta-group"><a className="button button-dark" href={hireHref}>Hire talent <span aria-hidden="true">↗</span></a><a className="button button-outline" href={jobsHref}>Find a role <span aria-hidden="true">↗</span></a></div></section></SiteShell>
}
